# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "default" namespace.
        server-urls: https://elasticsearch-sample-es-http:9200
          #use-aliases: true
          #tls.ca: /es/secrets/ca.crt
        tls.skip-host-verify: true
        username: elastic
        password: x4gDD9b0C3OFf272Xl4s9i7i
    #secretName: jaeger-secret
  volumeMounts:
    - name: secrets
      mountPath: /es/secrets/
      readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: elasticsearch-sample-es-http-certs-public
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking:
        gaID: UA-000000-2
      menu:
      - label: "About Jaeger"
        items:
          - label: "Documentation"
            url: "https://www.jaegertracing.io/docs/latest"
      linkPatterns:
      - type: "logs"
        key: "customer_id"
        url: /search?limit=20&lookback=1h&service=frontend&tags=%7B%22customer_id%22%3A%22#{customer_id}%22%7D
        text: "Search for other traces for customer_id=#{customer_id}"

