# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: default
spec:
  strategy: production
  collector:
    maxReplicas: 4
    resources:
      limits:
        cpu: 4000m
        memory: 2Gi
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "default" namespace.
        server-urls: https://elasticsearch-sample-es-http:9200
          #use-aliases: true
          #tls.ca: /es/secrets/ca.crt
        tls.skip-host-verify: true
        username: elastic
        password: 89xf0w2Hd86BhbkyF69Z4V6N
    #secretName: jaeger-secret
  volumeMounts:
    - name: secrets
      mountPath: /es/secrets/
      readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: elasticsearch-sample-es-http-certs-public
