# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: default
spec:
  strategy: production
  query:
    replicas: 1
    serviceType: LoadBalancer
    resources:
      requests:
        cpu: 4000m
        memory: 2Gi
  collector:
    replicas: 4
    autoscale: false
    resources:
      requests:
        cpu: 4000m
        memory: 2Gi
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elasticsearch-sample-es-http:9200
        tls.skip-host-verify: true
        username: elastic
        password: M1np29Szf4Rr8gA4XVU7337D
  volumeMounts:
    - name: secrets
      mountPath: /es/secrets/
      readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: elasticsearch-sample-es-http-certs-public
