apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: grpc-plugin # <1>
    grpcPlugin:
      image: busybox
    options:
      grpc-storage-plugin: # <3>
        configuration-file: /plugin-config/config.yaml
        log-level: debug
  volumeMounts:
    - name: plugin-config
      mountPath: /plugin-config
  volumes:
    - name: plugin-config
      configMap:
        name: jaeger-grpc
  ui:
    options:
      dependencies:
        menuEnabled: false
      tracking:
        gaID: UA-000000-2
      menu:
      - label: "About Jaeger"
        items:
          - label: "Documentation"
            url: "https://www.jaegertracing.io/docs/latest"
      linkPatterns:
      - type: "logs"
        key: "customer_id"
        url: /search?limit=20&lookback=1h&service=frontend&tags=%7B%22customer_id%22%3A%22#{customer_id}%22%7D
        text: "Search for other traces for customer_id=#{customer_id}"

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  podMetricsEndpoints:
  - port: admin-http

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-grpc
data:
  config.yaml: |
    GRPC_STORAGE_SERVER=tobs-promscale-connector.monitoring:9202