apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  query:
    replicas: 1
    serviceType: LoadBalancer
    resources:
      requests:
        cpu: 4000m
        memory: 2Gi
  collector:
    replicas: 4
    autoscale: false
    resources:
      requests:
        cpu: 4000m
        memory: 2Gi
  storage:
    type: grpc-plugin # <1>
    grpcPlugin:
      image: busybox
    options:
      grpc-storage-plugin: # <3>
        configuration-file: /plugin-config/config.yaml
        log-level: debug
  volumeMounts:
    - name: plugin-config
      mountPath: /plugin-config
  volumes:
    - name: plugin-config
      configMap:
        name: jaeger-grpc
