# setup an elasticsearch with `make es`
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
spec:
  strategy: production
  storage:
    type: elasticsearch
    options:
      es:
        # Note: This assumes elasticsearch is running in the "default" namespace.
        server-urls: https://elasticsearch-sample-es-http:9200
          #use-aliases: true
          #tls.ca: /es/secrets/ca.crt
        tls.skip-host-verify: true
        username: elastic
        password: t1IKQ5En86Bn84F1N4MfKT27
    #secretName: jaeger-secret
  volumeMounts:
    - name: secrets
      mountPath: /es/secrets/
      readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: elasticsearch-sample-es-http-certs-public
