{
 "title": "New dashboard",
 "time": { "from": "2022-10-03T19:51:45.957Z", "to": "2022-10-03T20:23:57.540Z" },
 "panels": [
  {
   "title": "Ingest",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(promscale_ingest_items_total{kind=\"span\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(jaeger_collector_spans_saved_by_svc_total{svc=\"tracegen\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger internals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(jaeger_collector_spans_dropped_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(jaeger_collector_queue_length[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(jaeger_collector_spans_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\".*simple-prod-collector.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jaeger CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*simple-prod-collector.*\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promscale Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod=~\".*promscale.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promscale CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\".*promscale.*\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TimescaleDB Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"tobs\", persistentvolumeclaim=\"storage-volume-tobs-timescaledb-0\"})))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"tobs\", persistentvolumeclaim=\"storage-volume-tobs-timescaledb-0\"})))\n)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_capacity_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"tobs\", persistentvolumeclaim=\"wal-volume-tobs-timescaledb-0\"})))\n  -\n  sum without(instance, node) (topk(1, (kubelet_volume_stats_available_bytes{cluster=\"\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"tobs\", persistentvolumeclaim=\"wal-volume-tobs-timescaledb-0\"})))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (by Namespace)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace!=\"\"}[1m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}