# this is a deployment for the tracegen utility that is delivered with Jaeger
# use with care, as it generates quite some load in the current setting
# this deployment was especially designed to test the autoscaling capabilities
# and requires an instance named 'simple-prod'.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracegen
  namespace: tracegen
# annotations:
#   "sidecar.jaegertracing.io/inject": "simple-prod"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tracegen
  template:
    metadata:
      labels:
        app: tracegen
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - jaeger
                - tobs-promscale
                - tobs-timescaledb
            topologyKey: kubernetes.io/hostname
      containers:
      - name: tracegen
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
        image: jaegertracing/jaeger-tracegen:1.36.0
        args:
        - -duration=8h
        - -workers=50
        - -pause=20ms
        env:
#       - name: JAEGER_AGENT_HOST
#         value: tobs-opentelemetry-collector.tobs
#       - name: JAEGER_AGENT_PORT
#         value: "6831"
        - name: JAEGER_ENDPOINT
          value: http://simple-prod-collector.default:14268/api/traces
          # value: http://tobs-opentelemetry-collector.tobs:14268/api/traces
      
